-- Minna social tables (profile + friends + friend requests)
create table if not exists public.minna_social_profiles (
  user_id text primary key,
  user_email text,
  nick text,
  bio text,
  goal text,
  avatar_url text,
  updated_at timestamptz default now()
);

create table if not exists public.minna_social_friends (
  owner_user_id text not null,
  owner_email text,
  friend_label text not null,
  friend_user_id text,
  friend_email text,
  created_at timestamptz default now(),
  primary key (owner_user_id, friend_label)
);

create table if not exists public.minna_social_friend_requests (
  id bigint generated by default as identity primary key,
  from_user_id text not null,
  from_email text not null,
  to_email text,
  to_user_id text,
  status text not null default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.minna_social_public_profiles (
  user_id text primary key,
  nick text,
  bio text,
  avatar_url text,
  updated_at timestamptz default now()
);

alter table public.minna_social_profiles enable row level security;
alter table public.minna_social_friends enable row level security;
alter table public.minna_social_friend_requests enable row level security;
alter table public.minna_social_public_profiles enable row level security;

do $$ begin
  alter table public.minna_social_friends add column if not exists friend_user_id text;
exception when others then null; end $$;
do $$ begin
  alter table public.minna_social_friends add column if not exists friend_email text;
exception when others then null; end $$;

do $$ begin
  create policy "profile_select_own" on public.minna_social_profiles for select using (auth.uid()::text = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "profile_upsert_own" on public.minna_social_profiles for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "friends_select_own" on public.minna_social_friends for select using (auth.uid()::text = owner_user_id or auth.uid()::text = friend_user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "friends_write_own" on public.minna_social_friends for all using (auth.uid()::text = owner_user_id) with check (auth.uid()::text = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.minna_social_friend_requests add column if not exists to_user_id text;
exception when others then null; end $$;
do $$ begin
  alter table public.minna_social_friend_requests alter column to_email drop not null;
exception when others then null; end $$;

do $$ begin
  create policy "requests_select_related" on public.minna_social_friend_requests for select using (
    auth.uid()::text = from_user_id or auth.uid()::text = to_user_id or lower(coalesce(auth.jwt()->>'email','')) = lower(coalesce(to_email,''))
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "requests_insert_sender" on public.minna_social_friend_requests for insert with check (
    auth.uid()::text = from_user_id and lower(coalesce(auth.jwt()->>'email','')) = lower(from_email)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "requests_update_related" on public.minna_social_friend_requests for update using (
    auth.uid()::text = from_user_id or auth.uid()::text = to_user_id or lower(coalesce(auth.jwt()->>'email','')) = lower(coalesce(to_email,''))
  ) with check (
    auth.uid()::text = from_user_id or auth.uid()::text = to_user_id or lower(coalesce(auth.jwt()->>'email','')) = lower(coalesce(to_email,''))
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "public_profiles_select_all" on public.minna_social_public_profiles for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public_profiles_write_own" on public.minna_social_public_profiles for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);
exception when duplicate_object then null; end $$;

-- Chat (direct + group)
create table if not exists public.minna_chat_threads (
  id bigint generated by default as identity primary key,
  thread_type text not null default 'direct', -- direct | group
  title text,
  owner_user_id text not null,
  created_at timestamptz default now()
);

create table if not exists public.minna_chat_participants (
  thread_id bigint not null references public.minna_chat_threads(id) on delete cascade,
  user_id text not null,
  joined_at timestamptz default now(),
  primary key (thread_id,user_id)
);

create table if not exists public.minna_chat_messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.minna_chat_threads(id) on delete cascade,
  from_user_id text not null,
  from_email text,
  body text not null,
  created_at timestamptz default now()
);

alter table public.minna_chat_threads enable row level security;
alter table public.minna_chat_participants enable row level security;
alter table public.minna_chat_messages enable row level security;

do $$ begin
  create policy "chat_threads_select_member" on public.minna_chat_threads for select using (
    exists(select 1 from public.minna_chat_participants p where p.thread_id=id and p.user_id=auth.uid()::text)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat_threads_insert_owner" on public.minna_chat_threads for insert with check (auth.uid()::text = owner_user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat_threads_update_owner" on public.minna_chat_threads for update using (auth.uid()::text = owner_user_id) with check (auth.uid()::text = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "chat_participants_select_member" on public.minna_chat_participants for select using (
    user_id=auth.uid()::text or exists(select 1 from public.minna_chat_participants p2 where p2.thread_id=thread_id and p2.user_id=auth.uid()::text)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat_participants_insert_member" on public.minna_chat_participants for insert with check (
    user_id=auth.uid()::text or exists(select 1 from public.minna_chat_threads t where t.id=thread_id and t.owner_user_id=auth.uid()::text)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat_participants_delete_self_or_owner" on public.minna_chat_participants for delete using (
    user_id=auth.uid()::text or exists(select 1 from public.minna_chat_threads t where t.id=thread_id and t.owner_user_id=auth.uid()::text)
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "chat_messages_select_member" on public.minna_chat_messages for select using (
    exists(select 1 from public.minna_chat_participants p where p.thread_id=minna_chat_messages.thread_id and p.user_id=auth.uid()::text)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat_messages_insert_sender" on public.minna_chat_messages for insert with check (
    from_user_id=auth.uid()::text and exists(select 1 from public.minna_chat_participants p where p.thread_id=minna_chat_messages.thread_id and p.user_id=auth.uid()::text)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat_messages_delete_sender" on public.minna_chat_messages for delete using (
    from_user_id=auth.uid()::text
  );
exception when duplicate_object then null; end $$;
