-- Minna social tables (profile + friends + friend requests)
create table if not exists public.minna_social_profiles (
  user_id text primary key,
  user_email text,
  nick text,
  bio text,
  goal text,
  avatar_url text,
  updated_at timestamptz default now()
);

create table if not exists public.minna_social_friends (
  owner_user_id text not null,
  owner_email text,
  friend_label text not null,
  friend_user_id text,
  friend_email text,
  created_at timestamptz default now(),
  primary key (owner_user_id, friend_label)
);

create table if not exists public.minna_social_friend_requests (
  id bigint generated by default as identity primary key,
  from_user_id text not null,
  from_email text not null,
  to_email text not null,
  status text not null default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.minna_social_public_profiles (
  user_id text primary key,
  nick text,
  bio text,
  avatar_url text,
  updated_at timestamptz default now()
);

alter table public.minna_social_profiles enable row level security;
alter table public.minna_social_friends enable row level security;
alter table public.minna_social_friend_requests enable row level security;
alter table public.minna_social_public_profiles enable row level security;

do $$ begin
  alter table public.minna_social_friends add column if not exists friend_user_id text;
exception when others then null; end $$;
do $$ begin
  alter table public.minna_social_friends add column if not exists friend_email text;
exception when others then null; end $$;

do $$ begin
  create policy "profile_select_own" on public.minna_social_profiles for select using (auth.uid()::text = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "profile_upsert_own" on public.minna_social_profiles for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "friends_select_own" on public.minna_social_friends for select using (auth.uid()::text = owner_user_id or auth.uid()::text = friend_user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "friends_write_own" on public.minna_social_friends for all using (auth.uid()::text = owner_user_id) with check (auth.uid()::text = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "requests_select_related" on public.minna_social_friend_requests for select using (
    auth.uid()::text = from_user_id or lower(coalesce(auth.jwt()->>'email','')) = lower(to_email)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "requests_insert_sender" on public.minna_social_friend_requests for insert with check (
    auth.uid()::text = from_user_id and lower(coalesce(auth.jwt()->>'email','')) = lower(from_email)
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "requests_update_related" on public.minna_social_friend_requests for update using (
    auth.uid()::text = from_user_id or lower(coalesce(auth.jwt()->>'email','')) = lower(to_email)
  ) with check (
    auth.uid()::text = from_user_id or lower(coalesce(auth.jwt()->>'email','')) = lower(to_email)
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "public_profiles_select_all" on public.minna_social_public_profiles for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public_profiles_write_own" on public.minna_social_public_profiles for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);
exception when duplicate_object then null; end $$;
